Added VideoControls class with play/pause, rewind, & > < buttons
CWRUbotixROV/rov-vision-22 pull request #16
Opened 2021-11-06 17:22 UTC by benjaminwp18

2021-11-07 19:29 UTC, ryankarpuszka requested changes
This is all working pretty well. Just some suggestions I had.

2021-11-07 19:29 UTC, ryankarpuszka commented on gui/app.py
> +    def __emit_frames(self):
I would only use one underscore at the beginning of this name

2021-11-07 19:29 UTC, ryankarpuszka commented on gui/app.py
> +        self.setLayout(self.horizontal_layout)
Could you try moving this to a separate file so we don't clutter this file up too much?

2021-11-07 19:29 UTC, ryankarpuszka commented on gui/app.py
> +            while self._thread_running_flag and not self._video_playing_flag:
You could get rid of the nested while loops to simplify things a bit.
```suggestion
            if self._video_playing_flag:
                self._emit_frames()
            
            self.msleep(...)
```

2021-11-07 19:30 UTC, ryankarpuszka commented
Resolves #12

2021-11-09 18:43 UTC, benjaminwp18 commented
I've made the changes you suggested; I can't believe I wrote that loop spaghetti.

2021-11-09 20:38 UTC, ryankarpuszka requested changes
There's still calls to `__emit_frames` instead of `_emit_frames`.

2021-11-09 20:38 UTC, ryankarpuszka commented on gui/app.py
> +from video_controls_widget import VideoControlsWidget
```suggestion
from gui.video_controls_widget import VideoControlsWidget
```

2021-11-09 21:04 UTC, ryankarpuszka approved these changes
Looks good!

2021-11-09 21:16 UTC, merged